config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :boards do
    get :grid, on: :member
    resources :players do
      resources :picks
    end
  end
  root 'boards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :players
  has_many :picks

  after_create :add_players

  def pick_player
    (picks.count % 2).zero? ? players.first : players.last
  end

  def player_name
    pick_player.try(:name).try(:capitalize)
  end

  def pick_column
    Pick.random_columns(self)
  end

  def ai_player?
    player_type == HUMAN_V_AI
  end

  private
    def add_players
      DEFAULT_PLAYER_NAMES.each do |name|
        players.create(name: name)
      end
    end

end

app/models/concerns/ai_player.rb
module AiPlayer
  extend ActiveSupport::Concern

  included do
  end

  def column_full?
     picks = self.board.picks.where(column: self.column)
     picks && picks.count == board.rows
  end

  def out_of_bounds?
    (self.column > (self.board.columns - 1) || self.column < 0)
  end
  
  module ClassMethods
    
    def random_columns(board)
      board.ai_player? ? hard_pick(board) : easy_pick(board)
    end

    def easy_pick(board)
      columns = 0.upto(board.columns - 1).to_a - board.picks.where(row: 1).map(&:column).flatten
      
      column  = columns.sample 
      columns.each do |col|
        if board.picks.where(column: col).count!= board.rows
          return col
        end
      end
    end

    def hard_pick(board)
      pay_on_row(board) || easy_pick(board)
    end

    def player_picks(board)
      return false if board.picks.count < 2
      board.picks.try(:last).try(:player).try(:picks)
    end

    def ai_picks(board)
      return false if board.picks.count < 2
      board.picks.where(player_id: board.players.last.id)
    end

    def pay_on_row(board)
      picks = player_picks(board)
      ai_picks = ai_picks(board)
      found_column = (pick_right_column(board, ai_picks) || pick_right_row(board, ai_picks)) if ai_picks
      found_column = (pick_right_column(board, picks) || pick_right_row(board, picks)) if picks && !found_column
      return found_column
    end

    def pick_right_column(board, picks)
      0.upto(board.columns - 1).each do |column|
        if board.picks.where(column: column).count!= board.rows && picks.where(column: column).count > 2 
          return  column
        end          
      end

      return false
    end

    def pick_right_row(board, picks)
      all_columns = 0.upto(board.columns - 1).to_a
      board.rows.downto(1).each do |row|
        row_picks = picks.where(row: row).order(:column)

        if row_picks.count > 2
          empty_columns = all_columns - row_picks.map(&:column)
          empty_columns.each do |rem_col|
            if board.picks.where(column: rem_col, row: row).empty?
              return rem_col
            end
          end   
        end
      end

      return false
    end
  end
end

app/models/concerns/winner.rb
module Winner
  extend ActiveSupport::Concern

  included do
  end

  module ClassMethods  
  end

  def current_picks
    @current_picks ||= board.picks.where(player_id: player_id).order(:row, :column)
  end

  def winner?
    current_picks.each do |pick|  
      if matching_pick?(pick, ROW) || matching_pick?(pick, COLUMN) ||
        matching_pick?(pick, D_RIGHT) || matching_pick?(pick, D_LEFT)
        return true
      end
    end

    return false
  end

  def matching_pick?(pick, type)
    found_pick = false
    matched_pick = 0
    1.upto(3) do |counters|
      if check_matched_pick?({type: type, row: pick.row, column: pick.column, counters: counters})
        matched_pick = matched_pick + 1
        if matched_pick == 3
          found_pick = true
          break
        end
      end
    end

    return found_pick
  end

  def check_matched_pick?(options = {})
    options = process_options(options)
    current_picks.where(row: options[:row], column: options[:column]).count > 0
  end

  def process_options(options = {})
    type = options[:type]
    counter = options[:counters]

    options[:row] = (options[:row] + counter) if [ROW, D_LEFT, D_RIGHT].include?(type)
    options[:column] = (options[:column] + counter) if [COLUMN, D_RIGHT].include?(type)
    options[:column] = (options[:column] - counter)  if type == D_LEFT
    options
  end

end

app/models/pick.rb
class Pick < ApplicationRecord
  include Winner
  include AiPlayer

  belongs_to :board
  belongs_to :player

  validates :board_id, presence: true
  validates :player_id, presence: true
  validates :row, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :column, presence: true

  after_create :set_winner?
  before_create :reset_row?

  def self.assign_row(options = {})
    board = Board.find_by(id: options[:board_id])
    picks = board.picks.where(column: options[:column])

    picks.count > 0 ? (picks.order(:row).first.row - 1) : board.rows
  end

  private

  def reset_row?
    if (column_full?) || out_of_bounds?
      self.column = self.easy_pick(self.board)
      self.row = self.assign_row({board_id: self.board.id, column: self.column})
    end
  end

  def set_winner?
    if winner?
      board.update_attribute(:winner, player.name)
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :board
  has_many :picks

  validates :board_id, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board
  before_action :set_picks
  
  def create
    redirect_to grid_board_path(@board)
  end

  private 
    def set_board
      @board ||= Board.find_or_create_by(id: params[:id])
      if params[:player_type].present?
        @board.update_attribute(:player_type, params[:player_type])
      end
    end

    def set_picks
      @picks ||= @board.try(:picks)
    end
    
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  skip_before_action :verify_authenticity_token,  :only => [:create]
  before_action :set_board
  
  def create
    add_pick_to_board
    redirect_to grid_board_path(@board)
  end

  private

    def set_board
      @board = Board.find_by(id: params[:board_id])
    end

    def add_pick_to_board
      Pick.create(
        board: @board,
        player_id: params[:player_id],
        column: pick_params[:column],
        row: assign_row
      )
    end

    def pick_params
      params.require(:pick).permit(
        :column,
        :row
      )
    end

    def assign_row
      options = {
        board_id: params[:board_id], 
        column: pick_params[:column],
      }
      Pick.assign_row(options)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper

  def pick_color_class(picks, options={})
    return 'empty-cell' if picks.empty?
    if picks.present?
      if pick = picks.find_by(row: options[:row], column: options[:column])
        pick.try(:player).try(:name)
      else
        'empty-cell'
      end
    end
  end

  def toggle_player

  end


  def no_winner?(picks,board)
    if picks.present? && board.present? && board.winner.nil?
      picks.count == (board.rows * board.columns)
    end
  end
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/boards/_board.html.erb
<div class="row"></div>
<% 1.upto(@board.rows) do |row| %>
  <% @board.columns.times do |column| %>
    <div class="col-sm-1 board-cell <%=pick_color_class(@picks, {row: row, column: column})%>" id="row_<%=row%>_column_<%=column%>">
    </div>
  <% end %>
  <div class="row"></div>
<% end %>

app/views/boards/_form.html.erb
<%= form_for Pick.new,remote: true, url: board_player_picks_path(@board, @board.pick_player), :html => { id: 'pick_form', :method => 'POST' } do |f|%>
  <%= f.hidden_field :column, value: @board.pick_column %>
<% end %>

<% unless @board.winner.present?%>
  <script>
  $(document).ready(function(){
    $('div.empty-cell').click(function(){
      id  = this.id;
      id  = id.split("_");
      // $('#pick_row').val(id[1])
      
      id  = id[id.length-1];
      
      $('#pick_column').val(id);
      $("#pick_form").submit();
      $("#pick_form").attr('action', window.location.href);
      $("#pick_form").attr('method', 'GET');
    });
  });
  </script>


  <% if ((@board.player_type == HUMAN_V_AI) && (@board.player_name == 'Pink')) %>
    <script>
        // $('#pick_column').val(<%=@board.pick_column%>);
        $("#pick_form").submit();
        $("#pick_form").attr('action', window.location.href);
        $("#pick_form").attr('method', 'GET');
      
    </script>
  <% end %>
<% end %>

app/views/boards/_player.html.erb
<% if @board.winner.present? %>
  <h1>
    <%= "Winner:: #{@board.winner.try(:capitalize)}" %>
  </h1>
<% elsif no_winner?(@picks,@board) %>
   <h1> No Winner for this Game</h1>
<% else %>
  <h1>
  <%= "Player:: #{@board.player_name}" %>
</h1>
<% end %>

app/views/boards/_start_new.html.erb
<div class='container' style='padding:10px;'>
  <div class="row">
    <div class="col-sm-4">
        <%= link_to boards_path(player_type: HUMAN_V_HUMAN), method: 'POST', class: 'btn btn-info' do %>
        Start New Game(Human vs Human)
        <% end %>
        <br/>
    </div>
    <div class="col-sm-4">
        <%= link_to boards_path(player_type: HUMAN_V_AI), method: 'POST', class: 'btn btn-info' do %>
        Start New Game(Human vs AI)
        <% end %>
    </div>
  </div>
</div>

app/views/boards/grid.html.erb
<%= render 'player' %>
<%= render 'board' %>
<%= render 'form' %>
<%= render 'start_new' %>

app/views/boards/index.html.erb
<div class="container">
  <h1>Welcome to Connect Four Game</h1>
  <%= render 'start_new' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Connect4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container' style='padding:10px;'>
      <div class="row">
        <div class="col-sm-4">
          <h3>Connect 4 Game</h3>
           <h4>Created By Tulasee Chintha using Rails</h4>
        </div>
      </div>
    </div>

    <%= yield %>
  </body>
</html>